[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
AstroCoords = "27fb9038-6a9d-4e07-8d5d-d0805b53c4cb"
AstroForceModels = "077569d7-e100-45f3-83e3-c646e23345bd"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ExperimentalDesign = "4babbea4-9e7d-11e9-116f-e1ada04bd296"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SatelliteToolboxGravityModels = "bd9e9728-6f7b-4d28-9e50-c765cb1b7c8c"
SatelliteToolboxTransformations = "6b019ec1-7a1e-4f04-96c7-a9db1ca5514d"
